//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacie
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int idproduit { get; set; }
        public string designationprod { get; set; }
        public string dosage { get; set; }
        public string forme { get; set; }
        public int quatitestock { get; set; }
        public Nullable<int> refcategorie { get; set; }
        public double Pu { get; set; }
    }
}
